# Generated by Django 6.0 on 2025-12-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_transaction_guest_email_transaction_is_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Purchase')], max_length=20),
        ),
    ]
