# Generated by Django 6.0 on 2025-12-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_price_service_provider_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized (Held)'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('VOIDED', 'Voided (Released)')], default='PENDING', max_length=10),
        ),
    ]
