# Generated by Django 6.0 on 2025-12-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='kashier_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kashier_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AUTHORIZED', 'Authorized (Held)'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('VOIDED', 'Voided (Released)')], default='PENDING', max_length=20),
        ),
    ]
