#system/settings.py
"""
Django settings for system project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""




from pathlib import Path
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env_path = BASE_DIR / '.env'
load_dotenv(dotenv_path=env_path)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

BASE_URL = os.getenv('BASE_URL', "http://localhost:8000")

ALLOWED_HOSTS = ['158.220.126.228', 'shaikly.com', 'www.shaikly.com', 'localhost']

AUTH_USER_MODEL = 'authentication.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'authentication',
    'rest_framework',
    'django_filters',
    'rest_framework.authtoken',
    'corsheaders',
    'store',
    "phonenumber_field",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'), # Default to localhost if missing
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS':{'min_length':8}
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'authentication.validators.CustomPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    
    # 1. Add Pagination (Limit to 20 items per page)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 5,

    # 2. Add Filtering (Allow ?search= and ?ordering= in URL)
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

CSRF_TRUSTED_ORIGINS = [
    'http://shaikly.com',
    'https://shaikly.com',
    'http://www.shaikly.com',
    'https://www.shaikly.com',
    'http://158.220.126.228',
    'https://api.shaikly.com',
    
]

# 2. Add your domain here so browser allows data sharing
CORS_ALLOWED_ORIGINS = [
    'http://shaikly.com',
    'https://shaikly.com',
    'http://www.shaikly.com',
    'https://www.shaikly.com',
    'http://158.220.126.228',
    "http://localhost:3000", #remove
    "http://127.0.0.1:3000", 
    
    "http://158.220.126.228:3000",
    "http://localhost:5174", #remove
    "http://localhost:5173",
]
CORS_ALLOW_CREDENTIALS = True


# 1. Credentials
KASHIER_MID = os.getenv("MERCHANT_ID") 
KASHIER_API_KEY = os.getenv("KASHIER_PAYMENT_API_KEY")
KASHIER_SECRET_KEY = os.getenv("KASHIER_SERVER_KEY") 
KASHIER_WEBHOOK_URL = os.getenv('KASHIER_WEBHOOK_URL', f"{BASE_URL}/store/transactions/webhook/kashier/")

# 2. Environment Setup
KASHIER_TEST_MODE = os.getenv('KASHIER_TEST_MODE', 'False') == 'True' 

CONVERSION_API_KEY = os.getenv("CONVERSION_API_KEY")

SICKW_API_KEY = os.getenv("SICKW_API_KEY")

if KASHIER_TEST_MODE:
    KASHIER_API_URL = "https://test-api.kashier.io" 
else:
    KASHIER_API_URL = "https://api.kashier.io"


# ==========================================
# EMAIL CONFIGURATION (SMTP)
# ==========================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Host: smtp.gmail.com (for Gmail) or smtp.live.com (for Outlook)
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')

# Port: 587 (TLS) is standard
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))

EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Your Email Credentials
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# The email address that appears in the "From" field
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)